---
- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker
  package:
    name: docker-ce
    state: present

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Copy docker-compose
  copy: 
    src=/vagrant/docker/docker-compose.sh
    dest=/usr/bin/docker-compose

- name: Turn on execute permission for docker-compose
  file: 
    path=/usr/bin/docker-compose
    mode="a+x"

- name: Creates directory
  file: path=/vagrant/dob state=directory

- name: Create docker-compose.yml
  template: 
    src:   docker-compose.yml.j2
    dest:  /vagrant/dob/docker-compose.yml
    owner: vagrant 
    group: vagrant 
    mode:  0644
