---
- hosts: jenkins
  become: true
  vars:
    my_jenkins_plugins:
      build-pipeline-plugin:
        enabled: yes
      ssh:
        enabled: yes
      ssh-slaves:
        enabled: yes
      git:
        enabled: yes
      github:
        enabled: yes
      log-parser:
        enabled: yes
      copyartifact:
        enabled: yes
      workflow-aggregator:
        enabled: yes
      workflow-multibranch:
        enabled: yes
      docker-workflow:
        enabled: yes
      template-project:
        enabled: yes
  roles:
    - firewall
    - { role: firewall-open-port, port: 8080 }
    - git
    - java
    #~ - reboot
    - jenkins
