---
- name: Add Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Add Jenkins repository
  get_url:
    url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    dest: '/etc/yum.repos.d/jenkins.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Jenkins
  package:
    name: jenkins,graphviz,monit,crontabs,libxml2,libxml2-devel,libxslt-devel,python-jenkins
    state: present

- name: Update Jenkins config
  template: 
    src:   config.xml.j2
    dest:  "{{ jenkins_home }}/config.xml"
    owner: "{{ jenkins_process_user }}" 
    group: "{{ jenkins_process_group }}" 
    mode:  0644

- name: Update Jenkins CLI config
  template: 
    src:   jenkins.CLI.xml.j2
    dest:  "{{ jenkins_home }}/jenkins.CLI.xml"
    owner: "{{ jenkins_process_user }}" 
    group: "{{ jenkins_process_group }}" 
    mode:  0644

- name: Create user {{ jenkins_admin_username }} with password {{ jenkins_admin_password }}
  script: /vagrant/jenkins/jenkins-create-user.sh {{ jenkins_admin_username }} {{ jenkins_admin_password }} {{ jenkins_home }} {{ jenkins_process_user }} {{ jenkins_process_group }}

- name: Create jenkins init script
  template: 
    src:   jenkins.sysconfig.j2
    dest:  /etc/sysconfig/jenkins
    owner: root 
    group: root 
    mode:  0644

- name: Ensure Jenkins is started and enabled at boot
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for jenkins to be available
  uri:
    url:  "http://localhost:8080/login"
  register: resp
  until: resp.status|default(false) == 200
  retries: 10
  delay: 10

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: present
    timeout: 30
    url: http://localhost:8080
    with_dependencies: yes
  with_items: "{{ jenkins_plugins }}"
  ignore_errors: yes

- name: restart jenkins
  service: name=jenkins state=restarted

- name: Wait for jenkins to be available
  uri:
    url:  "http://localhost:8080/login"
  register: resp
  until: resp.status|default(false) == 200
  retries: 10
  delay: 10
  
- name: Enable Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: enabled
    timeout: 30
    url: http://localhost:8080
    with_dependencies: yes
  with_items: "{{ jenkins_plugins }}"
  ignore_errors: yes

- name: restart jenkins
  service: name=jenkins state=restarted

- name: Wait for jenkins to be available
  uri:
    url:  "http://localhost:8080/login"
  register: resp
  until: resp.status|default(false) == 200
  retries: 10
  delay: 10

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no

- name: Add credentials to Jenkins
  script: /vagrant/jenkins/jenkins-add-credentials.sh http://localhost:8080 {{ jenkins_admin_username }} {{ jenkins_admin_password }}

- name: Add Jenkins slave node
  script: /vagrant/jenkins/jenkins-add-node.sh http://localhost:8080 {{ jenkins_admin_username }} {{ jenkins_admin_password }} {{ jenkins_slave_host }} vagrant

- name: Create Jenkins job
  jenkins_job:
    config: "{{ lookup('template', 'templates/job.xml.j2') }}"
    name: Docker-GitHub-SoftUni
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: http://localhost:8080
